### ISSUE TITLE
Cannot install azure-cli 1.0 on ubuntu using npm.

### ISSUE THREAD

**Issue by akramwaseem** [Azure/azure-docs-cli-python#1006]
Not sure what causing the issue but it is very annoying and I cannot find other ways apart from installing it through npm.
Let me know if there is any other way to install azure cli in ubuntu 14

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bfdd999-341a-7aa8-04cf-f3808d813051
* Version Independent ID: 76d4e553-fdd3-8339-6a11-870d53efdeb2
* Content: [Install the Azure CLI 1.0](https://docs.microsoft.com/en-us/cli/azure/install-cli-version-1.0?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-cli-version-1.0.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-cli-version-1.0.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Unfortunately we do not offer another way to install the CLI 1.0. The current install instructions are the only methods available.
