### ISSUE TITLE
Missing option?

### ISSUE THREAD

**Issue by mairaw** [Azure/azure-docs-cli-python#1023]
If I try to run the command as is, I get an error. Shouldn't the command be provided that would work with no modifications?

```console
maira@Azure:~$ az vm create -n MyLinuxVM -g MyResourceGroup --image UbuntuLTS
An RSA key file or key value must be supplied to SSH Key Value. You can use --generate-ssh-keys to let CLI generate one for you
maira@Azure:~$ az vm create -n MyLinuxVM -g MyResourceGroup --image UbuntuLTS --generate-ssh-keys
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b233e045-b444-e6d9-7893-36a72ee4a70b
* Version Independent ID: f2c47d3a-4976-ebe4-e732-e7c18dd4bed8
* Content: [Overview of Azure CLI 2.0](https://docs.microsoft.com/en-us/cli/azure/?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/index.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/index.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
This looks like a bug or internal `help` issue. Can you file with the engineering team? https://github.com/azure/azure-cli/issues

**Comment by onedumbtrucker** [comment]
Still open? I get the same issue.
