### ISSUE TITLE
 az account set --subscription with subscription name seems not work

### ISSUE THREAD

**Issue by bliu70** [Azure/azure-docs-cli-python#1024]
Why this is not working?
==
$ az account list --output table
Name                                         CloudName    SubscriptionId                        State    IsDefault
-------------------------------------------  -----------  ------------------------------------  -------  -----------
IT/Starlight Sandbox (AZR0754)               AzureCloud   0096221a-659a-4162-9ccf-93503db1a626  Enabled  False
az account set --subscription "IT/Starlight Sandbox"
The subscription of 'it/starlight sandbox' doesn't exist in cloud 'AzureCloud'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21632cd2-aec0-1521-a9b0-f96f69ab15ed
* Version Independent ID: d6ab81e8-1aba-b922-9984-4523386c83cf
* Content: [Manage Azure subscriptions with Azure CLI](https://docs.microsoft.com/en-us/cli/azure/manage-azure-subscriptions-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/manage-azure-subscriptions-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/manage-azure-subscriptions-azure-cli.md)
* Service: **active-directory**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@bliu70 - This sounds like a product bug. Please file an issue with the engineering team: https://github.com/azure/azure-cli/issues

**Comment by bliu70** [comment]
@sptramer I knew this is a bug in Azure or it's doc. I am surprised this is closed without being routed to a proper group within microsoft.
