### ISSUE TITLE
Pdf documentation link is broken

### ISSUE THREAD

**Issue by jagatsingh** [Azure/azure-docs-cli-python#1030]
The pdf documentation link does not open the pdf.

**Comment by sptramer** [comment]
@jagatsingh Please provide a link to the page which isn't generating PDF documentation. This request isn't specific enough.

**Comment by jagatsingh** [comment]
The download pdf link at bottom left of Azure Cli documentation.

https://docs.microsoft.com/en-us/cli/azure/opbuildpdf/azure-cli-latest/TOC.pdf?view=azure-cli-latest&branch=live
