### ISSUE TITLE
Install via PIP?

### ISSUE THREAD

**Issue by duncansmart** [Azure/azure-docs-cli-python#1052]
It appears the MSI is effectively just a python install and "az" is a PIP package. For those that already have a python install how about documenting that you can simply run `pip install azure-cli` to save installing the MSI?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8246b90a-efb1-03ce-f642-d3eb2441fc30
* Version Independent ID: 2fdd20ef-7bd3-57bc-7957-93f4bb5377ce
* Content: [Install the Azure CLI for Windows](https://docs.microsoft.com/en-gb/cli/azure/install-azure-cli-windows?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-windows.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli-windows.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by ryancrawcour** [comment]
The MSI doesn't appear to actually work though. I ran it a number of times and Python was never installed. The MSI just completed without any info / warnings / errors. But az was never installed.

**Comment by ryancrawcour** [comment]
If i run pip install azure-cli it appears to actually work, except i get these errors - 

zure-mgmt-datalake-analytics 0.2.0 has requirement msrestazure~=0.4.7, but you'll have msrestazure 0.5.0 which is incomatible.
zure-mgmt-recoveryservices 0.1.0 has requirement msrestazure~=0.4.11, but you'll have msrestazure 0.5.0 which is incomptible.
zure-mgmt-recoveryservicesbackup 0.1.1 has requirement msrestazure~=0.4.11, but you'll have msrestazure 0.5.0 which is incompatible.

**Comment by sptramer** [comment]
This is the reason why we don't document `pip` as an install option; there are many compatibility and requirement issues which can result from installing via `pip`.

**Comment by ryancrawcour** [comment]
Well, I am guessing that the MSI (if it worked) simply wraps this same pip install command and as such this is still going to be an issue, you probably just won't see it.

**Comment by ryancrawcour** [comment]
I am guessing that those 3 modules are out of date and need to be updated to support the correct version of msrestazure.

**Comment by ryancrawcour** [comment]
It's probably not a documentation issue though. I'll open another issue with engineering team to resolve. Thanks. You can close this.

**Comment by sptramer** [comment]
@duncansmart Our final determination on the `pip install` documentation is that we won't be officially providing it on the documentation site. While it's possible to install with `pip`, doing so can introduce a lot of errors, especially if a different install method is used later. `pip` is also not a language-agnostic install method.

For now our recommendation is that advanced users install with `pip`, and understand the complexities involved in updating any `pip` package which has numerous dependencies.
