### ISSUE TITLE
Input validation

### ISSUE THREAD

**Issue by mhausenblas** [Azure/azure-docs-cli-python#1061]
It seems that currently there is no validation of the input values. For example, `az configure --defaults location=blah` will work, though it shouldn't and will cause issues, down the line. Otherwise, great docs!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb42002e-9aa3-233d-9832-353235b7cd0f
* Version Independent ID: e8b320b1-5805-67ba-46b2-48111861facc
* Content: [Azure CLI configuration options](https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/azure-cli-configuration.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/azure-cli-configuration.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@mhausenblas If you would like to see input validation on defaults or other arguments, please file a feature request with the engineering team: https://github.com/azure/azure-cli/issues
