### ISSUE TITLE
Version number is out of date

### ISSUE THREAD

**Issue by ToddN** [Azure/azure-docs-cli-python#1065]
The documentation says the current version of the msi is 2.0.46, but when I click download, I get 2.0.47

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b7bd326-07b2-caaa-7155-5852fc2dfa3f
* Version Independent ID: c44d0547-d5cd-8934-00f8-79e2f4df53ac
* Content: [Install the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Documentation is updated daily at 3PM, including release notes and latest version for regular Tuesday releases.
