### ISSUE TITLE
Unpacking azure-cli (2.0.47-1~xenial) over (2.0.45-1~xenial) freezes on microsoft/vsts-agent:ubuntu-16.04-standard

### ISSUE THREAD

**Issue by razidare** [Azure/azure-docs-cli-python#1084]
I am hosting my own Azure DevOps agents as Docker containers on AKS starting from the image:

> FROM microsoft/vsts-agent:ubuntu-16.04-standard

Trying to install the latest version of az cli on the agents as per [this article](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest).

Always on the unpacking step, the console just freezes with no sign of downloading packages or error whatsoever: 

> Unpacking azure-cli (2.0.47-1\~xenial) over (2.0.45-1\~xenial) ...

Is there a way to see progress on this? The Unpacking just seems frozen and the exec fails at some point.
When I try to `kubectl exec -it myvstsagent /bin/bash` I get the following error:

`kubectl exec -it vstsagent-jb2-5dd6598f66-wr4pp /bin/bash -n vstsagents`
`error: unable to upgrade connection: pod does not exist`

However, I can see the pod is running:
`kubectl get po -n vstsagents `
`NAME                                           READY     STATUS    RESTARTS   AGE `
`vstsagent-jb2-5dd6598f66-wr4pp   1/1       Running        0          24m`

**Comment by sptramer** [comment]
To see the progress of an `apt` operation, pipe to `debconf-apt-progress`. See [this StackOverflow question](https://askubuntu.com/questions/245808/view-progress-of-a-package-installation-in-terminal).
