### ISSUE TITLE
Is Python a pre-requisite? 

### ISSUE THREAD

**Issue by ryancrawcour** [Azure/azure-docs-cli-python#1109]
I ran the installer, it says it succeeded, but when i open PowerShell (or CMD) to run az anything, it says it doesn't recognize az. 

I've been searching online and people say it's because a python scripts folder isn't in my PATH. 
If this is true, that would imply Python is a dependency but the documentation doesn't mention this anywhere, and the installer succeeds (i'd expect it to either install the missing components, or at least fail). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8246b90a-efb1-03ce-f642-d3eb2441fc30
* Version Independent ID: 2fdd20ef-7bd3-57bc-7957-93f4bb5377ce
* Content: [Install the Azure CLI for Windows](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-windows.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli-windows.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by ryancrawcour** [comment]
I just installed Python, then ran pip install azure-cli and now it appears the CLI has been installed. 
For some reason the MSI just does nothing.
Could be the same issue as a closed issue (MSI + Docker).

**Comment by sptramer** [comment]
@ryancrawcour Can you please report the MSI issue to engineering? https://github.com/azure/azure-cli

**Comment by ryancrawcour** [comment]
https://github.com/Azure/azure-cli/issues/7720

**Comment by ryancrawcour** [comment]
So, in short, yes Python is a pre-requisite, at the moment b/c the MSI isn't doing what it should be doing. Thanks.
