### ISSUE TITLE
`az account list` shows wrong `Name`

### ISSUE THREAD

**Issue by lietu** [Azure/azure-docs-cli-python#1110]
I've got access to 3 subscriptions on Azure. To make identifying them in the CLI tools I decided to rename them each to be `&lt;Project&gt; Pay-As-You-Go`. Now that's clearly visible in the Azure Portal, but `az account list` still just lists `Pay-As-You-Go` three times.

It's been weeks since I changed the name, so it's unlikely to be any caching or similar.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21632cd2-aec0-1521-a9b0-f96f69ab15ed
* Version Independent ID: d6ab81e8-1aba-b922-9984-4523386c83cf
* Content: [Manage Azure subscriptions with the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/manage-azure-subscriptions-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/manage-azure-subscriptions-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/manage-azure-subscriptions-azure-cli.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@lietu - This sounds like a product bug. Please file an issue with the engineering team. https://github.com/azure/azure-cli/issues
