### ISSUE TITLE
Latest version installed via apt-get, but not reflecting in az

### ISSUE THREAD

**Issue by Dawny33** [Azure/azure-docs-cli-python#1116]
I followed all the commands for updating the azure-cli version, so that the last line shows me this: `azure-cli is already the newest version (2.0.49-1~xenial). `

However, when I do `az --version`, it shows me the following: `azure-cli (2.0.22)`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1526a9-7f22-504e-484c-0f3edc11b178
* Version Independent ID: c5dec108-efcd-aa77-04b5-803b6b894dba
* Content: [Install the Azure CLI on Linux with apt](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-apt.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli-apt.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by MicahMcKittrick-MSFT** [comment]
@sptramer can you take a look at this one?

**Comment by sptramer** [comment]
@Dawny33 Please provide the following information:

- The results of `which az`
- Whether or not you installed the CLI using a non-apt method at any point

**Comment by Dawny33** [comment]
`/anaconda/envs/py35/bin/az`

I am not sure about the second part.  I dont remember installing az via a non-apt method

**Comment by sptramer** [comment]
It looks like you're using a Python virtual environment to run Azure CLI, which would have been installed with `pip` in that location. If you are in a venv, you should be able to type `deactivate` to escape it. At that point you should have access to the apt installed Azure CLI.

Without direct access to your machine I can't troubleshoot this for you aside from this guess.
