### ISSUE TITLE
getting error on my yocto bassed linux after downloading the run fails as below 

### ISSUE THREAD

**Issue by initmahesh** [Azure/azure-docs-cli-python#1121]

**Comment by sptramer** [comment]
@initmahesh I did not encounter this issue when running the Docker build produced as of 2018-11-06:

```
 ~  docker pull microsoft/azure-cli:latest
latest: Pulling from microsoft/azure-cli
ff3a5c916c92: Already exists
471170bb1257: Already exists
d487cc70216e: Already exists
9358b3ca3321: Already exists
d4d73eb5841d: Already exists
38a5e0ba3de7: Pull complete
b75c64e80eb9: Pull complete
031361571db5: Pull complete
Digest: sha256:32c29e710a31d3d205077dfd07af1415d3373818b9f013867e39c89d04faa2dc
Status: Downloaded newer image for microsoft/azure-cli:latest
 ~  docker run -it microsoft/azure-cli:latest
```

In the future if there is a problem running the latest image, please [file an issue with the engineering team](https://github.com/azure/azure-cli). We recommend using Docker images tagged with a specific version, as well.

**Comment by initmahesh** [comment]
can you confirm that you tested this on arm32v7 based OS flavor (eg. Raspberry pi 3) ..i discovered later that the issue was the docker image was build for x64 only and hence failing on my Linux based Yocto OS with arm32v7 architecture...

**Comment by sptramer** [comment]
Docker images depend on the host architecture and our Docker images are built for x86_64. File an issue with the engineering team if you would like an ARMv7 image.
