### ISSUE TITLE
MSI install with admin privilege

### ISSUE THREAD

**Issue by skamalj** [Azure/azure-docs-cli-python#1122]
MSI installer requires admin privileges, this is ok for home environment but not in office settings.   I have now set this up using :-
1. Conda (to setup separate new python environment for Pythin 3.6) 
2. Run pip install azure-cli.

This worked. and in addition does not required admin privileges.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8246b90a-efb1-03ce-f642-d3eb2441fc30
* Version Independent ID: 2fdd20ef-7bd3-57bc-7957-93f4bb5377ce
* Content: [Install the Azure CLI for Windows](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-windows.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli-windows.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@skamalj To ask for an officially supported distribution method which does not require administrator privileges on an MSI, please file an engineering issue: https://github.com/azure/azure-cli
