### ISSUE TITLE
No easy install without input in script version

### ISSUE THREAD

**Issue by msta** [Azure/azure-docs-cli-python#1123]
The InstallAzureCLI script doesn't seem to be able to run without input, which makes it quite hard to use in automated environments. The other option for CI builds seems to be the linux via apt, but updating the repos of a build server just for installing a CLI is just asking for trouble. Consider adding a --y or --no-input variable to the bash script. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b7bd326-07b2-caaa-7155-5852fc2dfa3f
* Version Independent ID: c44d0547-d5cd-8934-00f8-79e2f4df53ac
* Content: [Install the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@msta - Please file an issue with our engineering team requesting a non-interactive install mode: https://github.com/azure/azure-cli
