### ISSUE TITLE
Public Key Missing - Documentation removed

### ISSUE THREAD

**Issue by mlda065** [Azure/azure-docs-cli-python#1136]
I followed the steps [here](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest) to install the Azure cli with apt, and it failed when it got to ` sudo apt-add-repository ...`.

I'm pretty sure that pull request #1134 broke the instructions, by [removing the installation of Microsoft's key](https://github.com/Azure/azure-docs-cli-python/commit/22f727b8913869da558951bdc54f8399a861eeb9#diff-21a690694dd8b7eabb6411aabcf1c46e).

```
Reading package lists... Done
W: GPG error: https://packages.microsoft.com/repos/azure-cli bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF
E: The repository 'https://packages.microsoft.com/repos/azure-cli bionic InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

These instructions used to contain the command:
```
curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
```
When I run that command, I am able to continue and install the client with the remaining instructions.

When that command was removed, links to that section of the docs were not removed. So those links are now broken.

&gt; If you receive signing key errors, please ensure that you have acquired the [latest signing key](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#signingKey).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1526a9-7f22-504e-484c-0f3edc11b178
* Version Independent ID: c5dec108-efcd-aa77-04b5-803b6b894dba
* Content: [Install the Azure CLI on Linux with apt](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#signingKey)
* Content Source: [docs-ref-conceptual/install-azure-cli-apt.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli-apt.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@mlda065 - Can you please report the improper signing bug to engineering so they can resolve it as part of their distribution builds? https://github.com/azure/azure-cli/issues

**Comment by sptramer** [comment]
This should be fixed by reverting a bad change that went live shortly before this issue was filed. Sorry for the inconvenience, everything works now. There will be another small update to the apt instructions tomorrow to ensure that `curl` and `lsb-release` are properly installed before running the steps.
