### ISSUE TITLE
Try It

### ISSUE THREAD

**Issue by bhrionn** [Azure/azure-docs-cli-python#1141]
Cannot "Try it" and never could. Please help resolve why I cannot Try It on the webpage !?!?!

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b233e045-b444-e6d9-7893-36a72ee4a70b
* Version Independent ID: f2c47d3a-4976-ebe4-e732-e7c18dd4bed8
* Content: [Overview of the Azure CLI](https://docs.microsoft.com/en-ie/cli/azure/?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/index.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/index.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
I've been told that the "Try it" experience currently works as designed on our site. It launches the in-browser cloud shell experience, and it's up to users to copy-paste any code blocks into their cloud shell session. We're always working on improving the user experience of our site, and "try it" is one of the things that we're working to make better.
