### ISSUE TITLE
Cosmic Cuttlefish (18.10) Ubuntu Error

### ISSUE THREAD

**Issue by Luo-Liang** [Azure/azure-docs-cli-python#1156]
I have executed the command, but looks like it's not ready in 18.10?

ubuntu@PLinkDev:~/plink-marcopolo$ sudo apt-get update
Hit:1 http://azure.archive.ubuntu.com/ubuntu cosmic InRelease
Get:2 http://azure.archive.ubuntu.com/ubuntu cosmic-updates InRelease [83.2 kB]
Hit:3 http://azure.archive.ubuntu.com/ubuntu cosmic-backports InRelease
Ign:4 https://packages.microsoft.com/repos/azure-cli cosmic InRelease
Err:5 https://packages.microsoft.com/repos/azure-cli cosmic Release
  404  Not Found [IP: 13.91.48.226 443]
Get:6 http://security.ubuntu.com/ubuntu cosmic-security InRelease [83.2 kB]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1526a9-7f22-504e-484c-0f3edc11b178
* Version Independent ID: c5dec108-efcd-aa77-04b5-803b6b894dba
* Content: [Install the Azure CLI on Linux with apt](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-apt.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli-apt.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@Luo-Liang - Cosmic isn't in the list of supported versions on our install page. If you would like to see a Cosmic package, please file an issue with the engineering team so they can produce a build: https://github.com/azure/azure-cli/issues

**Comment by pjdv2** [comment]
@sptramer I filed an issue: https://github.com/Azure/azure-cli/issues/7918#issue-384499427.
