### ISSUE TITLE
MSI Version mismatch

### ISSUE THREAD

**Issue by akrone-hach** [Azure/azure-docs-cli-python#1162]
The downloaded version of the Azure CLI is 2.0.51 where the installation page shows 2.0.50 as the current version. The release notes for 2.0.51 haven't been updated either

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8246b90a-efb1-03ce-f642-d3eb2441fc30
* Version Independent ID: 2fdd20ef-7bd3-57bc-7957-93f4bb5377ce
* Content: [Install the Azure CLI for Windows](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-windows.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli-windows.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Our daily content publish is at 3PM Pacific. Releases tend to go live before then, so there is a short gap between when a new version is available and the release notes are up to date.

**Comment by akrone-hach** [comment]
@sptramer Good to know. Thanks!
