### ISSUE TITLE
Install Azure Cli with yum

### ISSUE THREAD

**Issue by pjdv2** [Azure/azure-docs-cli-python#1168]
It seems to go wrong in step 2 where the `echo -e` is added to the repo-file. This makes the `install` in step 3 also go wrong. If you then fix the repo-file manually you also get a list of errors (see below). I'm working on _Ubuntu 18.10_. I tried `--skip-broken` as suggested at the end of the error listing, but to no avail.

`azure-cli                                        | 2.9 kB  00:00     
azure-cli/primary_db                             |  30 kB  00:00     
Setting up Install Process
Resolving Dependencies
--> Running transaction check
---> Package azure-cli.x86_64 0:2.0.51-1.el7 will be installed
--> Processing Dependency: /bin/sh for package: azure-cli-2.0.51-1.el7.x86_64
--> Processing Dependency: libpthread.so.0(GLIBC_2.2.5)(64bit) for package: azure-cli-2.0.51-1.el7.x86_64
--> Processing Dependency: python for package: azure-cli-2.0.51-1.el7.x86_64
--> Processing Dependency: ld-linux-x86-64.so.2(GLIBC_2.3)(64bit) for package: azure-cli-2.0.51-1.el7.x86_64
--> Processing Dependency: rtld(GNU_HASH) for package: azure-cli-2.0.51-1.el7.x86_64
--> Processing Dependency: libc.so.6(GLIBC_2.4)(64bit) for package: azure-cli-2.0.51-1.el7.x86_64
--> Processing Dependency: /usr/bin/env for package: azure-cli-2.0.51-1.el7.x86_64
--> Processing Dependency: ld-linux-x86-64.so.2()(64bit) for package: azure-cli-2.0.51-1.el7.x86_64
--> Processing Dependency: libutil.so.1()(64bit) for package: azure-cli-2.0.51-1.el7.x86_64
--> Processing Dependency: libpthread.so.0()(64bit) for package: azure-cli-2.0.51-1.el7.x86_64
--> Processing Dependency: libm.so.6()(64bit) for package: azure-cli-2.0.51-1.el7.x86_64
--> Processing Dependency: libpython2.7.so.1.0()(64bit) for package: azure-cli-2.0.51-1.el7.x86_64
--> Processing Dependency: libdl.so.2()(64bit) for package: azure-cli-2.0.51-1.el7.x86_64
--> Processing Dependency: /usr/bin/env for package: azure-cli-2.0.51-1.el7.x86_64
--> Processing Dependency: /bin/sh for package: azure-cli-2.0.51-1.el7.x86_64
--> Finished Dependency Resolution
Error: Package: azure-cli-2.0.51-1.el7.x86_64 (azure-cli)
           Requires: ld-linux-x86-64.so.2()(64bit)
Error: Package: azure-cli-2.0.51-1.el7.x86_64 (azure-cli)
           Requires: libutil.so.1()(64bit)
Error: Package: azure-cli-2.0.51-1.el7.x86_64 (azure-cli)
           Requires: libpython2.7.so.1.0()(64bit)
Error: Package: azure-cli-2.0.51-1.el7.x86_64 (azure-cli)
           Requires: libpthread.so.0()(64bit)
Error: Package: azure-cli-2.0.51-1.el7.x86_64 (azure-cli)
           Requires: libm.so.6()(64bit)
Error: Package: azure-cli-2.0.51-1.el7.x86_64 (azure-cli)
           Requires: libpthread.so.0(GLIBC_2.2.5)(64bit)
Error: Package: azure-cli-2.0.51-1.el7.x86_64 (azure-cli)
           Requires: libdl.so.2()(64bit)
Error: Package: azure-cli-2.0.51-1.el7.x86_64 (azure-cli)
           Requires: ld-linux-x86-64.so.2(GLIBC_2.3)(64bit)
Error: Package: azure-cli-2.0.51-1.el7.x86_64 (azure-cli)
           Requires: /bin/sh
Error: Package: azure-cli-2.0.51-1.el7.x86_64 (azure-cli)
           Requires: python
Error: Package: azure-cli-2.0.51-1.el7.x86_64 (azure-cli)
           Requires: rtld(GNU_HASH)
Error: Package: azure-cli-2.0.51-1.el7.x86_64 (azure-cli)
           Requires: /usr/bin/env
Error: Package: azure-cli-2.0.51-1.el7.x86_64 (azure-cli)
           Requires: libc.so.6(GLIBC_2.4)(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
`

**Comment by sptramer** [comment]
Installing with `yum` (designed for RPM systems) may not be compatible with working on Ubuntu (which is designed to use `apt`). Please try the [apt install instructions](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest).

Ubuntu is also not listed as a supported platform for `yum` installs on our documentation. If you experience an issue with `yum` on RedHat-derived systems, [file an engineering bug](https://github.com/azure/azure-cli/issues).

**Comment by pjdv2** [comment]
> Installing with `yum` (designed for RPM systems) may not be compatible with working on Ubuntu (which is designed to use `apt`). Please try the [apt install instructions](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest).
> 
> Ubuntu is also not listed as a supported platform for `yum` installs on our documentation. If you experience an issue with `yum` on RedHat-derived systems, [file an engineering bug](https://github.com/azure/azure-cli/issues).

I realized that later as well. I tried `apt-get`, but couldn't get it to work. I then [manually](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?view=azure-cli-latest) installed it (though not recommended).

**Comment by sptramer** [comment]
Can you provide any more information about why the `apt` install failed? It could be because of the aborted/incomplete `yum` install creating incompatibilities. You may need to run some kind of cleanup operation in `yum`.

**Comment by pjdv2** [comment]
> Can you provide any more information about why the `apt` install failed? It could be because of the aborted/incomplete `yum` install creating incompatibilities. You may need to run some kind of cleanup operation in `yum`.

I removed `yum` and its content, but I think the problem is with the repository as it tries to search for the `cosmic` (Ubuntu 18.10) release. An issue has been created for this: https://github.com/Azure/azure-cli/issues/7776.

**Comment by sptramer** [comment]
OK, that's the case for sure. We do not have Cosmic packages yet, but the Bionic package may work on Cosmic. Thanks for confirming!
