### ISSUE TITLE
Error during installation on Ubuntu 18.10 (Cosmic Cuttlefish).

### ISSUE THREAD

**Issue by pjdv2** [Azure/azure-docs-cli-python#1174]
I get the following error (in red) during the manual install (using, the `curl -L https://aka.ms/InstallAzureCli | bash`):

`azure-mgmt-recoveryservices 0.1.0 has requirement msrestazure~=0.4.11, but you'll have msrestazure 0.5.1 which is incompatible.
azure-mgmt-recoveryservicesbackup 0.1.1 has requirement msrestazure~=0.4.11, but you'll have msrestazure 0.5.1 which is incompatible.
azure-mgmt-datalake-analytics 0.2.0 has requirement msrestazure~=0.4.7, but you'll have msrestazure 0.5.1 which is incompatible.`

I'm running _Ubuntu 18.10_ (Cosmic Cuttlefish).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7895b9a-9a6a-cd98-6947-0e4a26eda9a3
* Version Independent ID: a3f27295-3e2e-a36d-02c2-8897295fc443
* Content: [Install the Azure CLI for Linux manually](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-linux.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli-linux.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@pjdv2 - This looks like an issue in the module dependency information, which would need to be updated by the engineering team. Please file an issue with them.
