### ISSUE TITLE
keyserver receive failed: No dirmngr / E: Unable to locate package azure-cli

### ISSUE THREAD

**Issue by JosephCason** [Azure/azure-docs-cli-python#1175]
Tried install Azure CLI on Ubuntu shell on a brand new Windows 10 WSL and received the following two errors.

keyserver receive failed: No dirmngr 

@sp4jc1:~$ sudo apt-get install azure-cli
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package azure-cli

**Comment by sptramer** [comment]
Please see the [troubleshooting instructions](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#troubleshooting). This issue is specifically addressed.
