### ISSUE TITLE
Azure CLI

### ISSUE THREAD

**Issue by tobysharp** [Azure/azure-docs-cli-python#1207]
This page introduces Azure CLI but nowhere does it state what the acronym CLI stands for. In the interest of clarity this would be a good idea.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b233e045-b444-e6d9-7893-36a72ee4a70b
* Version Independent ID: f2c47d3a-4976-ebe4-e732-e7c18dd4bed8
* Content: [Overview of the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/index.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/index.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by StingyJack** [comment]
closed without a response?

CLI = Command Line Interface

**Comment by sptramer** [comment]
Issues which are closed directly by a pull request on GitHub don't receive updates on the site comment system. This comment was addressed by adding a definition at the top of the article.
