### ISSUE TITLE
Required connectivity

### ISSUE THREAD

**Issue by dcbrown16** [Azure/azure-docs-cli-python#1210]
I'm pretty sure you wouldn't be able to sign in (or do anything useful) if connections from your machine to the Internet are totally blocked. Could you sign in and use Azure CLI from a VM with an NSG allowing all Azure IPs?
In other words, what are the connectivity dependencies for using CLI?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93174b3a-3e97-8304-83fc-807be75198fe
* Version Independent ID: 1155045b-ce8c-2def-7b0e-043283f8be01
* Content: [Sign in with Azure CLI](https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/authenticate-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/authenticate-azure-cli.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
I believe that you only need the ability to reach Azure cloud endpoints, which should be possible from any VM hosted in Azure. If those endpoints aren't automatically available, you can get a whitelist of them from `az cloud show`. If that doesn't work, please reopen this issue and I'll get somebody from engineering to provide more concrete details.
