### ISSUE TITLE
Unable to install apt-key

### ISSUE THREAD

**Issue by dennismoon** [Azure/azure-docs-cli-python#1215]
The get Microsoft signing key install step does not work with the current version of Unbuntu from the Microsoft Store (Ubuntu 18.04.1 LTS). 

I get the error that ends with "gpg: keyserver receive failed: No dirmngr". 

The following workaround does not fix the issue:
sudo apt-get install dirmngr

I was able to get the Azure CLI installed on the current version of Unbuntu using the following steps:

sudo apt-mark hold ebtables # for the current upgrade bug

sudo apt-get update

sudo apt-get upgrade -y

sudo apt install apt-transport-https dirmngr

sudo apt-get update

sudo apt-get install apt-transport-https lsb-release software-properties-common -y
AZ_REPO=$(lsb_release -cs)
echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | \
    sudo tee /etc/apt/sources.list.d/azure-cli.list
	
sudo apt-get update

sudo apt-get install azure-cli

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1526a9-7f22-504e-484c-0f3edc11b178
* Version Independent ID: c5dec108-efcd-aa77-04b5-803b6b894dba
* Content: [Install the Azure CLI on Linux with apt](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-apt.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli-apt.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Please make sure that you follow the [Troubleshooting instructions for WSL](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#cli-fails-to-install-or-run-on-windows-subsystem-for-linux). There is a known issue with Linux IPC that affected older versions of WSL, and was fixed in Windows 10 1809.
