### ISSUE TITLE
botservice is not on the list of available extensions 12/26/2018

### ISSUE THREAD

**Issue by btk15** [Azure/azure-docs-cli-python#1223]
az extension add -n botservice
No matching extensions for 'botservice'. Use --debug for more information.

az extension list-available --output table 
does not list botservice either

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4067dde0-6db0-4e37-1a8e-fe5bb9324c62
* Version Independent ID: 8ba50218-429b-2c2a-eda6-8b1cfc62615f
* Content: [Available extensions for the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-list?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/azure-cli-extensions-list.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/azure-cli-extensions-list.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
The `botservice` extension has been removed.
