### ISSUE TITLE
I want to translate to ko_kr for "Install Azure CLI 2.0". Could you help?

### ISSUE THREAD

**Issue by ianychoi** [Azure/azure-docs-cli-python#228]
Hello,

I would like to translate https://docs.microsoft.com/en-us/cli/azure/install-azure-cli document into Korean (language code: ko_kr).

Actually, I am not too much familiar with Korean translation, but as far as I know, Korean translated documents are stored in: https://github.com/Azure/azure-content-kokr .

Then could you help where I contribute Korean translation? Just making a fork from here and creating a pull request to this repository would be fine?

With many thanks,

/Ian

**Comment by ericvt** [comment]
Hi @ianychoi and thank you for wanting to translate the Azure CLI install documentation in Korean.
It is our plan to have the entire Azure CLI articles in Korean, we are working on it.
We would love your feedback regarding the quality of the translation, may we contact you when we have those published?

**Comment by ianychoi** [comment]
Hello @ericvt ,

Sorry for my late reply - I am still now in US for travel.
My saying was originally that I wanted to participate in translation, not to just see Korean translated version of Azure CLI installation documentation.

Can I also participate in translating and/or reviewing Korean Azure CLI documentation?

I have been translating the document by forking from this repository and commiting on my local branch: 
https://github.com/ianychoi/azure-docs-cli-python/blob/ko-kr/docs-ref-conceptual/install-azure-cli.md
. If it is the right way to contribute my translation, I would like to continue and finish the translation for Azure CLI documentation.

Also, last week, I registered my account to https://www.transifex.com/microsoft-oss/ thanks to Terry Sheng, If I need to wait for the projects in Transifex for Azure CLI documentation, please tell me.

Or if you already had a plan working on it, please share your estimated schedule for me to wait for Korean translated version.

**Comment by ericvt** [comment]
thank you @ianychoi , I will put you in contact with Terry and @Sara-Nicolini to figure how we can partner together.

**Comment by sptramer** [comment]
@ericvt @ianychoi  - If you have been connected with our translation team, please close this issue.

**Comment by ianychoi** [comment]
@sptramer Thanks a lot for all kind help - I now see that the Korean translated version is available through: https://docs.microsoft.com/ko-kr/cli/azure/install-azure-cli?view=azure-cli-latest .
