### ISSUE TITLE
Recommend Python 3.6 on Windows install

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-docs-cli-python#270]
Currently, install recommends Python 3.5.
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli#windows

Would suggest Python 3.6 as 3.6 has a fix for the MAX_PATH limitation on Windows.
https://docs.python.org/3/using/windows.html#removing-the-max-path-limitation

**Comment by allclark** [comment]
I'm going to remove the version recommendation since we're really just repeating what the Python download page recommends.
