### ISSUE TITLE
Web Apps samples link on iverview page broken - returns 404

### ISSUE THREAD

**Issue by SpaceShot** [Azure/azure-docs-cli-python#279]
I visited the Azure CLI 2.0 overview page today at:
https://docs.microsoft.com/en-us/cli/azure/overview

I wanted to check out the Web Apps samples near the bottom of the page, but when clicking the link, I received a 404 page saying the page could not be found.

This is the link shown when hovering over the link in a browser:
https://docs.microsoft.com/en-us/azure/app-service/app-service-cli-samples?toc=%2fcli%2fazure%2ftoc.json&bc=%2fcli%2fazure%2fbreadcrumb%2ftoc.json

I think this link has been changed to:
https://docs.microsoft.com/en-us/azure/app-service-web/app-service-cli-samples?toc=%2fcli%2fazure%2ftoc.json&bc=%2fcli%2fazure%2fbreadcrumb%2ftoc.json

It might be easier to see the change by comparing across forks:
https://github.com/Azure/azure-docs-cli-python/compare/master...SpaceShot:patch-1

I came over to the GitHub repo to see if I can figure out how to fix and contribute, so I am figuring out how to build the docs and test locally, but have not tested this and would want to do so before submitting a pull request.

**Comment by allclark** [comment]
Thanks for pointing that out. Fix will go live today: https://github.com/Azure/azure-docs-cli-python/pull/282
