### ISSUE TITLE
Example az vm list --query "[].{VMName:name,OSType:storageProfile.osDisk.osType}" 

### ISSUE THREAD

**Issue by irwins** [Azure/azure-docs-cli-python#425]
Hi,

I'm trying my hand at azcli. Great examples on JMEPath queries, I had no idea this was a thing!
In the example --query "[].{VMName:name, OSType:storageProfile.osDisk.osType}" I needed to add an extra space behind the comma to get it to work... That worked for me... Just thought I'd drop a line letting you know...

Rg./Irwin

**Comment by sptramer** [comment]
@irwins Thanks for letting us know, and sorry for the delay in getting it fixed. Thank you!
