### ISSUE TITLE
The documentation and cli both confirm the --encrypt-format-all option but he running extension reports it is not supported, see below.

### ISSUE THREAD

**Issue by digeler** [Azure/azure-docs-cli-python#549]
https://docs.microsoft.com/en-us/cli/azure/vm/encryption?view=azure-cli-latest

[AzureDiskEncryption] 9716: [Info] Executing: yum install -y cryptsetup lsscsi psmisc cryptsetup-reencrypt lvm2 uid at patch procps-ng util-linux gcc libffi-devel openssl-devel python-devel
AAzureDiskEncrytion] 9716: [Info] Executing: pip show adal
AzureDiskEncrAzureDiskEncryption] 9716: [Info] Command pip show adal failed with return code 1
stdout:
stderr:
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[AzureDiskEncryption] 9716: [Info] Executing: pip install --upgrade six
[AzureDiskEncryption] 9716: [Ino] Executing: pip install adal
[AzureDiskEncryption] 9716: [Info] Data volume /my_data is mounted from /dev/sd1
[AzureDiskEncryption] 9716: [Info] Data volume /my_data2 is mounted from /dev/sdd1
2017/11/20 11:34:03.083512 INFO Event: name=Microsoft.Azure.Security.AzureDiskEncryptionForLinux, op=Install, message=Launch command succeeded: main/handle.py -install, duration=0
2017/11/20 11:34:03.090569 INFO [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-0.1.0.999306] Enable extension [main/handle.py -enable]
[AzureDiskEncrytion] 10117: [Ifo] Enabling exension
[AzureDiskEncryption] 10117: [Ifo] Public settings:
{
    'AADClientCertThumbprint': null, 
    'AADClientID': ******, 
    'EncryptionOperation': 'EnableEncryptionFormatAll', 
    'KeyEncryptionAlgorithm': 'RSA-OAEP', 
    'KeyEncryptionKeyURL': '*****disks.vault.azure.net/keys/testl01/a0f*****', 
    'KeyVaultURL': '*******', 
    'SequenceVersion': '656a0648-d89f-48d7-872b-7403d768ef25', 
    'VolumeType': 'ALL'
}
[AzureDiskEncryption] 10117: [Info] **Encryption operation EnableEncryptionFormatAll is not supported**
[AzureDiskEncryption] 10117: [Info] Executing: lvs --noheadings --nameprefixes --unquoted -o lv_name,vg_name,lv_kernel_major,lv_kernel_minor
AzureDiskEncryption] 10117: [Info] Data volume /my_data is mounted from /dev/sdc1
[AzureDiskEncryption] 10117: [Info] Data volume /my_data2 is mounted from /dev/sdd1

**Comment by sptramer** [comment]
@digeler  - Please file a bug with github.com/Azure/azure-cli, the inline documentation is maintained by the CLI engineering team and this sounds like a bug or misfeature.
