### ISSUE TITLE
Missing quotes in example

### ISSUE THREAD

**Issue by pjdm** [Azure/azure-docs-cli-python#576]
The example given here is missing quotes in the query

`az vm list --query [*].[name, resourceGroup] --out table`

and should be

`az vm list --query "[*].[name, resourceGroup]" --out table`

**Comment by Adam-Smith-MSFT** [comment]
@pjdm Thanks for the correction, I'll route it to the appropriate team to correct it.

**Comment by sptramer** [comment]
@pjdm @Adam-Smith-MSFT There is a pull request open for this issue. Please upvote it or include other activity so the CLI team is encouraged to process it.

https://github.com/Azure/azure-cli/pull/5066

**Comment by sptramer** [comment]
Fixed.
