### ISSUE TITLE
Latest update - 2018?

### ISSUE THREAD

**Issue by dcbrown16** [Azure/azure-docs-cli-python#603]
I believe Version 2.0.25 should be January 2018, not 2017 :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0e8d9ef-f25b-bb46-7f1a-bd3588be3343
* Version Independent ID: cd392600-a90d-0145-5ea6-6b01ab8f4ab9
* [Content](https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?toc=%2fcli%2fazure%2ftoc.json&bc=%2fcli%2fazure%2fbreadcrumb%2ftoc.json&view=azure-cli-latest)
* [Content Source](https://github.com/Azure/azure-docs-cli-python/blob/live/docs-ref-conceptual/release-notes-azure-cli.md)
* Service: multiple

**Comment by Adam-Smith-MSFT** [comment]
Thanks for the feedback @dcbrown16, I reached out to the content team to review your comment. 

Adam

**Comment by sptramer** [comment]
Closed by #605
