### ISSUE TITLE
What do the outputs mean?

### ISSUE THREAD

**Issue by dcbrown16** [Azure/azure-docs-cli-python#604]
Is there a resource somewhere that tells you what the meaning of the various properties in the JSON output are? For example, what's the difference between 'provisioningState' and 'status'?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48273ba7-da5a-95f0-7ffc-8c6d5282313d
* Version Independent ID: 83d348f9-fd1f-1041-0304-d8634e5526d4
* [Content](https://docs.microsoft.com/en-us/cli/azure/format-output-azure-cli?view=azure-cli-latest)
* [Content Source](https://github.com/Azure/azure-docs-cli-python/blob/live/docs-ref-conceptual/format-output-azure-cli.md)
* Service: multiple

**Comment by Adam-Smith-MSFT** [comment]
@dcbrown16
Thanks for the comment, there is a link which provides information about provisionningState and Status: 
The ProvisioningState status is returned as part of the Get information about a virtual machine API model and instance view responses and represents the state of the virtual machine from the Azure Resource Manager’s standpoint (the management layer of the virtual machine).
This link contains more information about the statuses: 
https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/virtualmachines-state
Let me know if this helps. 

Thanks,

**Comment by chwarr** [comment]
There's a more generic question here: for *any* given command, what is the schema of the JSON that I can expect when using `--output json`? Implicit in this question is that assumption that the JSON output is contractual and will be evolved in non-breaking ways (or new commands/switches will be added when there are breaking changes).

If this implicit contract is not intended, that really needs to be called out and very clearly.
Though, without this implicit contract, az isn't scriptable at all...

**Comment by dcbrown16** [comment]
It turned out that the customer in this case was asking about Web/serverfarms, the App Service Plans, so this was the relevant doc:
https://docs.microsoft.com/ja-jp/rest/api/appservice/appserviceplans/list#statusoptions
There isn't really a definition of what the statuses mean though.
Having some better guidance to work through the JSON output (the schema) would definitely be great if at all doable.

**Comment by sptramer** [comment]
Guidance on reading schema output is a known problem with reference materials, which is owned by the CLI engineering team. 

Issue https://github.com/Azure/azure-cli/issues/5761 has been created to address this as part of the CLI.
