### ISSUE TITLE
Installer version incorrect

### ISSUE THREAD

**Issue by pvrk** [Azure/azure-docs-cli-python#611]
The latest version mentioned in this page is 2.0.25 but the installer button in https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest page shows "2.0.26" and it fails to download

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0e8d9ef-f25b-bb46-7f1a-bd3588be3343
* Version Independent ID: cd392600-a90d-0145-5ea6-6b01ab8f4ab9
* [Content](https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest)
* [Content Source](https://github.com/Azure/azure-docs-cli-python/blob/live/docs-ref-conceptual/release-notes-azure-cli.md)
* Service: multiple

**Comment by sptramer** [comment]
I've alerted the CLI team so that they can investigate this problem.

**Comment by derekbekoe** [comment]
The most recent MSI will always be available at so no need for the aka.ms link which seemed to cause issues:
https://azurecliprod.blob.core.windows.net/msi/azure-cli-latest.msi

Related to https://github.com/Azure/azure-docs-cli-python/issues/607

**Comment by sptramer** [comment]
@pvrk Please confirm that you can get the latest install version so this issue can be closed.

**Comment by sptramer** [comment]
Closing issue due to lack of response and other reports of correct downloads.
