### ISSUE TITLE
Undated article

### ISSUE THREAD

**Issue by simeyla** [Azure/azure-docs-cli-python#616]
I get scared when I find an article like this for something that looks exactly like what I need - but there's no date anywhere. 
So I have no idea if it's 5 years old and now obsolete - or the latest and greatest way to manage my Azure account. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8246b90a-efb1-03ce-f642-d3eb2441fc30
* Version Independent ID: 2fdd20ef-7bd3-57bc-7957-93f4bb5377ce
* [Content](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest)
* [Content Source](https://github.com/Azure/azure-docs-cli-python/blob/live/docs-ref-conceptual/install-azure-cli-windows.md)
* Service: multiple

**Comment by Adam-Smith-MSFT** [comment]
Thanks for the feedback, I reached out to the content team to resolve the issue.
