### ISSUE TITLE
"az billing invoice list" requires optin

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-docs-cli-python#617]
Porting this over from azure-cli repo https://github.com/Azure/azure-cli/issues/5471

Can you please add link to documentation on how to opt-in to download invoices via azure CLI?

<del>Can there be an command in Azure CLI to opt-in?. It looks like going through UI pages again to opt-in seems like extra work</del>

cc @sethusrinivasan
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8866b243-5c18-7e9a-f233-0033d0eb64f9
* Version Independent ID: c98a81e3-ec68-5819-4a8f-897043f97371
* [Content](https://docs.microsoft.com/en-us/cli/azure/billing/invoice?view=azure-cli-latest)
* [Content Source](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-billing/azure/cli/command_modules/billing/_help.py)
* Service: unspecified

**Comment by sptramer** [comment]
@tjprescott Please email me with some details about this feature, including an example of how to run it. It seems like this should be CLI inline documentation, not a full conceptual article, unless there is substantial workflow involved.

**Comment by sptramer** [comment]
Detailed documentation for billing is already available: https://docs.microsoft.com/en-us/azure/billing/billing-manage-access

Closing this ticket.

**Comment by tjprescott** [comment]
That link is for managing access through the portal.  The user was requesting links to documents for the CLI.

**Comment by sptramer** [comment]
Is there an ability to do this through the CLI? The email you just sent indicated that this command doesn't exist yet.

**Comment by tjprescott** [comment]
As far as I know there isn't.
