### ISSUE TITLE
SSH from Azure CLI does not work

### ISSUE THREAD

**Issue by ohwellwhatever** [Azure/azure-docs-cli-python#618]
'ssh' is not recognized as an internal or external command,
operable program or batch file.

Should show Bash rather than Azure CLI for the SSH command following az vm create example.  Would also be good to reference other supported clients for Windows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c268a98-afcb-d2c2-87c7-880d52900533
* Version Independent ID: 4c835da4-38bc-22a8-67b4-dd522adcc0e3
* [Content](https://docs.microsoft.com/en-us/cli/azure/get-started-with-azure-cli?view=azure-cli-latest)
* [Content Source](https://github.com/Azure/azure-docs-cli-python/blob/live/docs-ref-conceptual/get-started-with-azure-cli.md)
* Service: multiple

**Comment by sptramer** [comment]
Has been fixed by PR #584.
