### ISSUE TITLE
This page would be more useful if it displayed latest version 

### ISSUE THREAD

**Issue by markSmurphy** [Azure/azure-docs-cli-python#626]
I know what version I have, via 'az -v' but I now only know if there's a newer version by downloading the .msi and running it.  Stating the latest version number would be useful.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8246b90a-efb1-03ce-f642-d3eb2441fc30
* Version Independent ID: 2fdd20ef-7bd3-57bc-7957-93f4bb5377ce
* [Content](https://docs.microsoft.com/en-gb/cli/azure/install-azure-cli-windows?view=azure-cli-latest)
* [Content Source](https://github.com/Azure/azure-docs-cli-python/blob/live/docs-ref-conceptual/install-azure-cli-windows.md)
* Service: multiple

**Comment by Adam-Smith-MSFT** [comment]
Thanks for the feedback @markSmurphy  , I will route it to the content team. 
Thanks

**Comment by sptramer** [comment]
The latest version is now displayed on the main install page.
