### ISSUE TITLE
yum check-update?

### ISSUE THREAD

**Issue by vincepower** [Azure/azure-docs-cli-python#637]
Why have the check-update? If the azure-cli requires something it will grab the update as part of the yum install or yum update command. yum check-update will just list other available updates on the system.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9f55d23-7802-e0da-6d12-b71f6da8a1d4
* Version Independent ID: 192846d7-baae-bcba-698b-22bdcdae468a
* [Content](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-yum?view=azure-cli-latest#feedback)
* [Content Source](https://github.com/Azure/azure-docs-cli-python/blob/live/docs-ref-conceptual/install-azure-cli-yum.md)
* Service: multiple

**Comment by sptramer** [comment]
Thanks for the report, this part of the instructions has been removed now.
