### ISSUE TITLE
Empty results on query for table output

### ISSUE THREAD

**Issue by gsacavdm** [Azure/azure-docs-cli-python#638]
Are there any special considerations with `-o table` that I should be aware of? Why does this not return any results?

```bash
az vm list --query "[].{id:id}" -o table
```

Yet this does:

```bash
az vm list --query "[].{id:id}" -o json
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48273ba7-da5a-95f0-7ffc-8c6d5282313d
* Version Independent ID: 83d348f9-fd1f-1041-0304-d8634e5526d4
* [Content](https://docs.microsoft.com/en-us/cli/azure/format-output-azure-cli?view=azure-cli-latest)
* [Content Source](https://github.com/Azure/azure-docs-cli-python/blob/live/docs-ref-conceptual/format-output-azure-cli.md)
* Service: multiple

**Comment by sptramer** [comment]
It looks like this is related to a known issue which is considered a feature request (https://github.com/Azure/azure-cli/issues/5434). Because there are multiple values contained within an array, the `table` output doesn't seem to know how to appropriately handle it.

**Comment by sptramer** [comment]
__Correction__: This is definitely a separate issue! The problem seems to be the length of the field. The documentation will still be updated but a feature request will need to be added to the CLI.

**Comment by sptramer** [comment]
The output format information has been updated to indicate that the `id` key is always stripped from `table` output.
