### ISSUE TITLE
Should be 'Ubuntu trusty, xenial, and artful' instead of 'Ubuntu wheezy, xenial, and artful'

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-docs-cli-python#644]
Minor change required in the text of the intro paragraph.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1526a9-7f22-504e-484c-0f3edc11b178
* Version Independent ID: c5dec108-efcd-aa77-04b5-803b6b894dba
* [Content](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest)
* [Content Source](https://github.com/Azure/azure-docs-cli-python/blob/live/docs-ref-conceptual/install-azure-cli-apt.md)
* Service: multiple

**Comment by sptramer** [comment]
Fixed by #645
