### ISSUE TITLE
thx...

### ISSUE THREAD

**Issue by kingterryofisrael** [Azure/azure-docs-cli-python#647]
I'm learning...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8246b90a-efb1-03ce-f642-d3eb2441fc30
* Version Independent ID: 2fdd20ef-7bd3-57bc-7957-93f4bb5377ce
* [Content](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest)
* [Content Source](https://github.com/Azure/azure-docs-cli-python/blob/live/docs-ref-conceptual/install-azure-cli-windows.md)
* Service: multiple

**Comment by bharat19th** [comment]
not able to download this MSI file

**Comment by sptramer** [comment]
@derekbekoe - We're still experiencing problems with downloads, even though the windows MSI download links now point directly to `azure-cli-latest.msi`. Could this be due to region, firewall, or proxy blocking on the customer end?

**Comment by derekbekoe** [comment]
@bharat19th please add your comments to https://github.com/Azure/azure-docs-cli-python/issues/607.
@sptramer we should close this issue.

**Comment by sptramer** [comment]
Closing in favor of #607.
