### ISSUE TITLE
Product Feedback link for pilot

### ISSUE THREAD

**Issue by tomresing** [Azure/azure-docs-cli-python#651]
Wouldn’t the [uservoice feedback channel for Azure CLI](https://feedback.azure.com/forums/216665-scripting-and-command-line-tools) be a better destination for product feedback? Currently, the product feedback link is https://github.com/Azure/azure-cli

**Comment by derekbekoe** [comment]
For product issues or feature suggestions, the GitHub repo is the best place since that's where the engineers on the product will look.
We have seen cases where issues like https://github.com/Azure/azure-cli/issues/5410 will be created but not sure if there's anything that can be done there.

**Comment by tomresing** [comment]
If Uservoice is not being monitored for feature suggestions, it would be great to make that clear. Currently, there seems to be a lot of activity there.

**Comment by sptramer** [comment]
@derekbekoe Close this issue when you feel appropriate.

**Comment by derekbekoe** [comment]
@sptramer I do not have permission to close in the repo.
