### ISSUE TITLE
provide documentation on how to get az cli version

### ISSUE THREAD

**Issue by prashanthmadi** [Azure/azure-docs-cli-python#656]
> az --version 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b233e045-b444-e6d9-7893-36a72ee4a70b
* Version Independent ID: f2c47d3a-4976-ebe4-e732-e7c18dd4bed8
* [Content](https://docs.microsoft.com/en-us/cli/azure/overview?view=azure-cli-latest#feedback)
* [Content Source](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/overview.md)
* Service: multiple

**Comment by Adam-Smith-MSFT** [comment]
Thanks for the feedback, I'll loop the content team to examine the suggestion.
