### ISSUE TITLE
Add Upsert option on Most Resources

### ISSUE THREAD

**Issue by nirmalparekh1984** [Azure/azure-docs-cli-python#657]
Currently, most resources only have create, update, delete, show, list... 
Adding an upsert (Update Or Insert) option will be beneficial from DevOps Automation using cli, it would reduce coding where in developer first has to check if resource exists then then implement either insert or update operation 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b233e045-b444-e6d9-7893-36a72ee4a70b
* Version Independent ID: f2c47d3a-4976-ebe4-e732-e7c18dd4bed8
* [Content](https://docs.microsoft.com/en-us/cli/azure/overview?view=azure-cli-latest)
* [Content Source](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/overview.md)
* Service: multiple

**Comment by Adam-Smith-MSFT** [comment]
Thanks for the feedback, I'll loop the content team in to examine the suggestion.

**Comment by sptramer** [comment]
This is a feature request. @nirmalparekh1984 please file a feature request issue at https://github.com/Azure/azure-cli
