### ISSUE TITLE
pip as CLI installation option?

### ISSUE THREAD

**Issue by bridgetkromhout** [Azure/azure-docs-cli-python#665]
Would it make sense, since python is required and we mention package managers, for this page to recommend installation via pip? `pip install --user azure-cli` should work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7895b9a-9a6a-cd98-6947-0e4a26eda9a3
* Version Independent ID: a3f27295-3e2e-a36d-02c2-8897295fc443
* [Content](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?view=azure-cli-latest)
* [Content Source](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli-linux.md)
* Service: multiple

**Comment by bridgetkromhout** [comment]
Specifically, we could link here: https://pypi.python.org/pypi/azure-cli

**Comment by sptramer** [comment]
cc @derekbekoe - I'm assuming that we want to continue to leave `pip` off of the recommended install options?

**Comment by derekbekoe** [comment]
We want to leave it off yes but we always will support installation with pip since it's the defacto Python Package Manager. From our experience, we found it to be an 'advanced' scenario with many people not being familiar with pip, running into issues then blaming the CLI.

**Comment by derekbekoe** [comment]
But if you want to use pip, that's fine!

**Comment by derekbekoe** [comment]
@sptramer We could add it and add a note that it's more advanced and the other installers are recommended but seems like users who are familiar with pip would know to use it anyway.

**Comment by sptramer** [comment]
If it causes issues where users mistakenly file bug reports, then it seems worth leaving it off for the time being. Is there anything that could be done to make PyPy the install source of record?

**Comment by bridgetkromhout** [comment]
> We could add it and add a note that it's more advanced and the other installers are recommended but seems like users who are familiar with pip would know to use it anyway.

Sure, of course - but it looks kinda disconnected from the community for us to ignore something that people know is the standard.

Unless we're struggling with the mentioned mistaken bug reports, I'd really rather make it clear in the docs we're connected to where the community is.
