### ISSUE TITLE
How to Change Tenants?

### ISSUE THREAD

**Issue by joshbooker** [Azure/azure-docs-cli-python#667]
As a CSP partner I have access to several client tenancies - each having multiple subscriptions.  When I list subscriptions I only get those in my own default tenancy.  Is there a cli option to change tenants?  Or is my only option to auth using tenant admin of respective client tenancy?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21632cd2-aec0-1521-a9b0-f96f69ab15ed
* Version Independent ID: d6ab81e8-1aba-b922-9984-4523386c83cf
* [Content](https://docs.microsoft.com/en-us/cli/azure/manage-azure-subscriptions-azure-cli?view=azure-cli-latest)
* [Content Source](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/manage-azure-subscriptions-azure-cli.md)
* Service: multiple

**Comment by joshbooker** [comment]
figured it out:
az login --username <myEmailAddress> -t <customerTenantId-or-Domain>
az account set --subscription <clientSubscriptionId>

**Comment by mrdfuse** [comment]
Thanks, it certainly helped me.
