### ISSUE TITLE
Chocolatey Package

### ISSUE THREAD

**Issue by gep13** [Azure/azure-docs-cli-python#668]
As you may be aware, a Chocolatey Community Member has created a Chocolatey Package for the Azure CLI.  This makes it easy to install it on a Windows machine using:

`choco install azure-cli`

In the same way that it is recommended to install on say a Mac using:

`brew install azure-cli`

Would someone in this team be interested in taking ownership of that package to ensure that it is kept up to date with new releases?

Would you accept a PR to add this information to the install section of the docs for Windows?

**Comment by gep13** [comment]
The Chocolatey Package can be found here:

https://chocolatey.org/packages/azure-cli

**Comment by sptramer** [comment]
We would prefer to maintain documentation only for officially supported install channels.

cc @derekbekoe re: ownership

**Comment by gep13** [comment]
>@sptramer said...
We would prefer to maintain documentation only for officially supported install channels.

I totally understand that.  

Is there anything to stop Chocolatey becoming a supported install channel, in the same way that brew on Mac is supported?

**Comment by derekbekoe** [comment]
Currently, there are installers for the most common platforms, including the MSI for Windows, and it's unfeasible for us to support every single installer.

It's great to see a community contributed package and we have an issue tracking this:
https://github.com/Azure/azure-cli/issues/3874

@gep13 Do you have download numbers for installs through chocolatey?
If it is a common install path, we can consider increasing the priority of the above issue.

Thanks!

**Comment by sptramer** [comment]
Closing this so that discussion can move over to azure/azure-cli#3874 - centered on official support for a package type, not docs.

**Comment by gep13** [comment]
The downloads stats for that package can be seen on the package page here:

https://chocolatey.org/packages/azure-cli

Which is not a small number by any means.

Does this help influence the decision? Given that a community package already exists, the amount of work required to take it over would be minimal, and definitely something that we could help getting you set up with.
