### ISSUE TITLE
RFE: Repo RPM to install RPM gpg public keys and Yum/DNF .repo files to install azure-cli w/ using yum

### ISSUE THREAD

**Issue by ssato** [Azure/azure-docs-cli-python#679]
I prefer to maintain these files as package rather than arrange them manually by following instructions here.
Could you please consider to provide such RPM to install GPG public key and .repo files?
(I made an experimental RPM SPEC to accomplish this: https://github.com/ssato/misc/blob/master/rpmspecs/azure-cli-repos.spec)

If so, instructions will become much simple such like the following:

- install: yum install -y the_repo_rpm_url (or dnf install -y ...)
- uninstall: yum remove -y the_repo_rpm_name
- remove gpg public key: sudo rpm -e $(rpm -qa gpg-pubkey\* --qf "%{v}-%{r} %{summary}\n" | awk '/Microsoft/ { print "gpg-pubkey-"$1; }')

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9f55d23-7802-e0da-6d12-b71f6da8a1d4
* Version Independent ID: 192846d7-baae-bcba-698b-22bdcdae468a
* Content: [Install the Azure CLI 2.0 on Linux with yum | Microsoft Docs](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-yum?view=azure-cli-latest#)
* Content Source: [docs-ref-conceptual/install-azure-cli-yum.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli-yum.md)
* Service: **multiple**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@derekbekoe Feature request, please respond here and move over to Azure/azure-cli

**Comment by derekbekoe** [comment]
> Could you please consider to provide such RPM to install GPG public key and .repo files?

@ssato Can you expand on this? Also, please open an issue at https://github.com/Azure/azure-cli
