### ISSUE TITLE
AADSTS90023: Couldn't get valid user code

### ISSUE THREAD

**Issue by yogevh** [Azure/azure-docs-cli-python#714]
I get this message after trying to az login.
after getting the code, i enter it in the specified link. then i need to login with my Azure User and finally i get this error and cannot move forward to work with Azure CLI.

I didn't find anything online regarding this error
please assist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c268a98-afcb-d2c2-87c7-880d52900533
* Version Independent ID: 4c835da4-38bc-22a8-67b4-dd522adcc0e3
* Content: [Get started with Azure CLI 2.0](https://docs.microsoft.com/en-us/cli/azure/get-started-with-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/get-started-with-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/get-started-with-azure-cli.md)
* Service: **multiple**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@derekbekoe - This looks like an OAuth2 infrastructure error. Is there any indication of a bug somewhere or what can be done?

@yogevh - This is an older ticket. Can you still not log in, and if you can't, can you provide some more details about your account? Such as if you're using a different cloud than Azure Public, or have 2FA enabled.

**Comment by derekbekoe** [comment]
@yugangw-msft may be able to help?

**Comment by yugangw-msft** [comment]
@yogevh  are you using corporate microsoft account?

**Comment by HighwayofLife** [comment]
I ran into this error as well using an Azure Private cloud using the configuration for authenticating with active directory into a kubernetes cluster. I've followed the steps in [Azure Active Directory plugin for client authentication](https://github.com/kubernetes/client-go/blob/master/plugin/pkg/client/auth/azure/README.md). I'm authenticating with my corporate credentials for my company.

**Comment by yugangw-msft** [comment]
@bganapa , assume `Azure Private` == `Azure Stack`, then I don't think device code has ever worked there. Can you clarify?

**Comment by HighwayofLife** [comment]
Azure Private cloud is the same as public cloud, but with private network and express route to your on prem network.

**Comment by sptramer** [comment]
Closing this issue - looks like it's resolved and also there has been a lack of activity.

**Comment by HighwayofLife** [comment]
I found that this was because our corp uses a Netskope client to route all traffic, and traffic not going through that client (i.e. if the client is disabled) would interfere with the ability to login to our SAML single sign-on process. The solution was to enable the Netskope client, and then the AZ login was able to succeed.
