### ISSUE TITLE
Don't --password

### ISSUE THREAD

**Issue by RonWang** [Azure/azure-docs-cli-python#731]
az login -u <username> -p <password>

Is it correct to have the password as a direct input? This may lead to unintentional password leak!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93174b3a-3e97-8304-83fc-807be75198fe
* Version Independent ID: 1155045b-ce8c-2def-7b0e-043283f8be01
* Content: [Log in with Azure CLI 2.0](https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/authenticate-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/authenticate-azure-cli.md)
* Service: **multiple**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@RonWang This is correct - there are many alternatives to logging in with a username/password. If you would like to make a feature request or improvement with the CLI team, please file a GitHub issue at http://github.com/azure/azure-cli.

**Comment by rsmith54** [comment]
The workaround should likely be made into the default behavior.  There are other examples throughout the docs where this warning is not displayed.

https://docs.microsoft.com/en-us/azure/storage/common/storage-azure-cli

for example.
