### ISSUE TITLE
small bug in the HDI NSG documentation

### ISSUE THREAD

**Issue by lsilvamiguel** [Azure/azure-docs-cli-python#735]
While walking through this information on our public documentation on creating NSG rules using PowerShell:
https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-extend-hadoop-virtual-network?toc=%2Fen-us%2Fazure%2Fhdinsight%2Fstorm%2FTOC.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json#azure-powershell 

I’ve found a small bug in the code on the very last line:

$vnet | Set-AzureRmVirtual Network

Should be

$vnet | Set-AzureRmVirtualNetwork

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93174b3a-3e97-8304-83fc-807be75198fe
* Version Independent ID: 1155045b-ce8c-2def-7b0e-043283f8be01
* Content: [Log in with Azure CLI 2.0](https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/authenticate-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/authenticate-azure-cli.md)
* Service: **multiple**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@lsilvamiguel - Please file a bug against Azure PowerShell documentation.
