### ISSUE TITLE
Microsoft Repos doesn't exist for latest Ubuntu 18.04 LTS Bionic

### ISSUE THREAD

**Issue by MaxKhlupnov** [Azure/azure-docs-cli-python#755]
Err:6 https://packages.microsoft.com/repos/azure-cli bionic Release
  404  Not Found [IP: 13.80.10.205 443]
Reading package lists... Done
E: The repository 'https://packages.microsoft.com/repos/azure-cli bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1526a9-7f22-504e-484c-0f3edc11b178
* Version Independent ID: c5dec108-efcd-aa77-04b5-803b6b894dba
* Content: [Install the Azure CLI 2.0 on Linux with apt](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-apt.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli-apt.md)
* Service: **multiple**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by derekbekoe** [comment]
See https://github.com/Azure/azure-cli/issues/5731
