### ISSUE TITLE
Zypper install command should be updated

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-docs-cli-python#791]
FROM
```
sudo zypper install -y azure-cli
```
TO
```
sudo zypper install --from azure-cli -y azure-cli
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26961ab6-af63-1bb9-53d1-566e4acc2896
* Version Independent ID: 2c26a785-ca52-321a-ba33-4622ed9d37a2
* Content: [Install the Azure CLI 2.0 on Linux with zypper](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-zypper?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-zypper.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli-zypper.md)
* Service: **unspecified**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Closed by #786
