### ISSUE TITLE
blob snapshot not shown in az storage blob list . CLI version 2.0.32 

### ISSUE THREAD

**Issue by chenghao1983** [Azure/azure-docs-cli-python#810]
![image](https://user-images.githubusercontent.com/17667607/40040602-7e50a6dc-584d-11e8-8c54-f6b9a93f4eb4.png)

![image](https://user-images.githubusercontent.com/17667607/40040448-e8bd31c6-584c-11e8-85cc-146cd2327760.png)

The blob has snapshot. However CLI shows null. Please help fix.

Besides, appreciate if next CLI could list down all snapshots.

Thanks !

**Comment by twitchax** [comment]
Hi @chenghao1983, can you please file this against Azure/azure-cli?

Please include the command that you are running and the `--debug` spew, as well.

@sptramer, please close (also, feel free to give me permissions). :)

**Comment by sptramer** [comment]
Closing this issue since it is a product bug.
