### ISSUE TITLE
"Sign in on an Azure VM using MSI" link broken

### ISSUE THREAD

**Issue by richardspitz** [Azure/azure-docs-cli-python#823]
I was looking for information on signing into Azure using "az" on a VM which has MSI enabled (Answer: You can do this using "az login -i" from MSI enabled VM)

I get a 404 for the linked page:
https://docs.microsoft.com/en-us/azure/active-directory/msi-how-to-get-access-token-using-msi?toc=%2fcli%2fazure%2ftoc.json&bc=%2fcli%2fazure%2fbreadcrumb%2ftoc.json&view=azure-cli-latest

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93174b3a-3e97-8304-83fc-807be75198fe
* Version Independent ID: 1155045b-ce8c-2def-7b0e-043283f8be01
* Content: [Log in with Azure CLI 2.0](https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/authenticate-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/authenticate-azure-cli.md)
* Service: **active-directory**
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@richardspitz - Thank you for the broken link report. This should be fixed in today's site publish.
