### ISSUE TITLE
Determining Ubuntu release name under Linux Mint

### ISSUE THREAD

**Issue by wmpauli** [Azure/azure-docs-cli-python#846]
This documentation works well for Linux Mint, except that the environment variable AZ_REPO needs to be set different, like so:
AZ_REPO=`grep "UBUNTU_CODENAME" /etc/os-release | cut -f 2 -d '='`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1526a9-7f22-504e-484c-0f3edc11b178
* Version Independent ID: c5dec108-efcd-aa77-04b5-803b6b894dba
* Content: [Install the Azure CLI 2.0 on Linux with apt](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-apt.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli-apt.md)
* Service: **unspecified**
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by wmpauli** [comment]
Thank you. That makes sense.

**Comment by sptramer** [comment]
@wmpauli To help users better understand why the install process might not work on derived distributions, some help has been added to the "Troubleshooting" section. Thanks for your suggestion, we want to make sure the CLI is easy to install on every platform.
