### ISSUE TITLE
reference link broken

### ISSUE THREAD

**Issue by ivan-shaporov** [Azure/azure-docs-cli-python#864]
"A detailed reference is also available that documents how to use each individual Azure CLI 2.0 command." The "reference" link points to https://docs.microsoft.com/en-us/cli/azure/reference-index which returns 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b233e045-b444-e6d9-7893-36a72ee4a70b
* Version Independent ID: f2c47d3a-4976-ebe4-e732-e7c18dd4bed8
* Content: [Azure CLI 2.0](https://docs.microsoft.com/en-us/cli/azure/?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/index.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/index.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by dend** [comment]
Can repro - am currently working on a fix.

**Comment by sptramer** [comment]
Reference link seems to be fixed, closing issue.
