### ISSUE TITLE
Common command link for web applications is broken

### ISSUE THREAD

**Issue by mrbullwinkle** [Azure/azure-docs-cli-python#872]
Link currently goes to: [https://docs.microsoft.com/en-us/azure/ap-service](https://docs.microsoft.com/en-us/azure/ap-service) I am assuming you want it to go: [https://docs.microsoft.com/en-us/azure/app-service](https://docs.microsoft.com/en-us/azure/app-service)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c268a98-afcb-d2c2-87c7-880d52900533
* Version Independent ID: 4c835da4-38bc-22a8-67b4-dd522adcc0e3
* Content: [Get started with Azure CLI 2.0](https://docs.microsoft.com/en-us/cli/azure/get-started-with-azure-cli?view=azure-cli-latest#common-commands)
* Content Source: [docs-ref-conceptual/get-started-with-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/get-started-with-azure-cli.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Thank you for the report. This link should be fixed during tomorrow's site publish.
