### ISSUE TITLE
Broken link to Cloud Shell page

### ISSUE THREAD

**Issue by nunix** [Azure/azure-docs-cli-python#887]
When clicking on the Cloud Shell links, it tries to get to the page [https://github.com/Azure/azure-docs-cli-python/blob/master/azure/cloud-shell/overview](https://github.com/Azure/azure-docs-cli-python/blob/master/azure/cloud-shell/overview) and this ends up in a 404 error.

Not sure which page is correct, so hopefully you do :)

Best regards,
Nuno

**Comment by sptramer** [comment]
@nunix Which page was the incorrect link on?

**Comment by nunix** [comment]
The ones I saw are here:
https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/index.md

Not sure if other files have it though

**Comment by sptramer** [comment]
I see, the issue is that you're viewing the documentation on github and not on the microsoft site. Please go to https://docs.microsoft.com/cli/azure to see the documentation.
