### ISSUE TITLE
Supported versions and releases of Windows

### ISSUE THREAD

**Issue by blooregard** [Azure/azure-docs-cli-python#889]
Is there a list of support versions/releases of Windows?  Some of my co-workers on Windows are having problems running the CLI and PowerShell commands, while I don't have those issues on my Mac (10.13.5).  Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b7bd326-07b2-caaa-7155-5852fc2dfa3f
* Version Independent ID: c44d0547-d5cd-8934-00f8-79e2f4df53ac
* Content: [Install the Azure CLI 2.0](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@twitchax - Do we have any required version support beyond the listed requirements of PowerShell version?

@blooregard - To resolve this we need more information on which versions of Windows do not seem to be compatible, which version of PowerShell is running, and which module (AzureRM or AzureRM.Core) was installed.

**Comment by twitchax** [comment]
@sptramer, PowerShell version should not matter for the CLI.  I would need more information, as you requested to evaluate what the issue may be here.

**Comment by sptramer** [comment]
Misread the repo name. Used to bug reports like this ending up in PowerShell.

**Comment by blooregard** [comment]
We found the root cause on https://github.com/Azure/azure-cli/issues/4626
