### ISSUE TITLE
Cannot install CLI package on win10 embedded Ubunto 18

### ISSUE THREAD

**Issue by allanpoulsen** [Azure/azure-docs-cli-python#894]
When following the instructions on:
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest

The step:
sudo apt-get install apt-transport-https

I get:
allan@AP-ZBOOK:~$ sudo apt-get install apt-transport-https
E: Malformed entry 1 in list file /etc/apt/sources.list.d/azure-cli.list (Component)
E: The list of sources could not be read.
E: Malformed entry 1 in list file /etc/apt/sources.list.d/azure-cli.list (Component)
E: The list of sources could not be read.

Any ideas?
Regards,
Allan

**Comment by sptramer** [comment]
Delete the offending file (`/etc/apt/sources.list.d/azure-cli.list`) and try following the instructions again: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest

**Comment by allanpoulsen** [comment]
Is CLI 2.0 not supported in Ubunto 18, running embedded on Win10 ?

**Comment by sptramer** [comment]
@allanpoulsen There is not an official Bionic package available. See the top of the install page for the complete list of supported distributions. If you would like to try installing the Xenial package, you can manually set `AZ_REPO` to `xenial` rather than running `lsb_release`.
