### ISSUE TITLE
Download link broken

### ISSUE THREAD

**Issue by alastairs** [Azure/azure-docs-cli-python#917]
The download link appears to be broken. It resolves to https://azurecliprod.azureedge.net/msi/azure-cli-2.0.41.msi, which displays the following message in my browser:

> BlobNotFoundThe specified blob does not exist. RequestId:6eb95e84-701e-00a3-52f2-127685000000 Time:2018-07-03T17:23:52.2932519Z

Note that v2.0.39 is available at https://azurecliprod.azureedge.net/msi/azure-cli-2.0.39.msi, modified from above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8246b90a-efb1-03ce-f642-d3eb2441fc30
* Version Independent ID: 2fdd20ef-7bd3-57bc-7957-93f4bb5377ce
* Content: [Install the Azure CLI for Windows](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest#install-or-update)
* Content Source: [docs-ref-conceptual/install-azure-cli-windows.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli-windows.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
It looks like the "latest" links are being updated before the packages actually go live. Release 2.0.41 is scheduled to be published this afternoon. This is an engineering process issue, not a docs problem.

cc @twitchax - please make sure MSIs are published before updating redirects.

**Comment by troydai** [comment]
Please retry.
