### ISSUE TITLE
readme broken links

### ISSUE THREAD

**Issue by kbroughton** [Azure/azure-docs-cli-python#927]
These links are now broken.
The Azure CLI 2.0 provides the following commands to manage role assignments.

    az role assignment list
    az role assignment create
    az role assignment delete

**Comment by sptramer** [comment]
These links all work correctly. Please make sure you are viewing the documentation on the Microsoft site. 
https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?view=azure-cli-latest
