### ISSUE TITLE
How to run az CLI on a headless ubuntu?

### ISSUE THREAD

**Issue by dogmarcopolo** [Azure/azure-docs-cli-python#939]
Just installed az cli on a headless ubuntu inside AWS (that is how we intend to use the cli). the issue i have is that there is no gui associated with the VM (due to strict firewall rule, can't redirect x windows back to my desktop). so:

'az login' doesn't work. 'az login --use-device-code' provided a code but that doesn't help since i could only enter the code on my desktop machine.

so my question is how do i get az cli to work in this configuration without creating a windows vm (cost more) in AWS?

**Comment by sptramer** [comment]
Probably the best way to do this would be to log into Azure through the portal, and create a service principal for use with the Azure CLI. See: https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?view=azure-cli-latest#sign-in-using-the-service-principal
