### ISSUE TITLE
install fails (package not found) for linux mint 19 -- fix

### ISSUE THREAD

**Issue by SteveDevOps** [Azure/azure-docs-cli-python#955]
Users of linux mint 19 will need to alter the repo url after the fact as AZ_REPO=$(lsb_release -cs) produces "tara main"  which doesn't exist in ms repo -- change / alter via software sources tool to trusty main. Then update apt cache and rerun install.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1526a9-7f22-504e-484c-0f3edc11b178
* Version Independent ID: c5dec108-efcd-aa77-04b5-803b6b894dba
* Content: [Install the Azure CLI 2.0 on Linux with apt](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-apt.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli-apt.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Our instructions do not list Linux Mint as a supported platform, and provide details that users need to manually set `AZ_REPO` for Debian/Ubuntu-derived distributions due to this exact reported issue.
