### ISSUE TITLE
-timeout parameter

### ISSUE THREAD

**Issue by dcbrown16** [Azure/azure-docs-cli-python#968]
For an advisory support, case, I'm looking for the default value and/or min/max values of the -timeout parameter on `az storage blob download`.
Can you share that info, or where I can find it?

**Comment by sptramer** [comment]
This should be documented in the reference help, or from the `-h` output. If the information is not there, please file a bug with the engineering team, which manages the reference: https://github.com/azure/azure-cli/issues
