### ISSUE TITLE
if mapping the ${HOME} volume when starting the Docker container - az autocompletion doesn't work by default

### ISSUE THREAD

**Issue by cicorias** [Azure/azure-docs-cli-python#974]
When the -v ${HOME}:/root is passed to docker, since there probably is a different .bashrc file in the home directory, the az autocompletion doesn't work by default.   

One way to fix is to create one. On windows this goes in c:\Users\&lt;user&gt;  - 
# .bashrc
_python_argcomplete() {
    local IFS=$'\013'
    local SUPPRESS_SPACE=0
    if compopt +o nospace 2&gt; /dev/null; then
        SUPPRESS_SPACE=1
    fi
    COMPREPLY=( $(IFS="$IFS" \
                  COMP_LINE="$COMP_LINE" \
                  COMP_POINT="$COMP_POINT" \
                  COMP_TYPE="$COMP_TYPE" \
                  _ARGCOMPLETE_COMP_WORDBREAKS="$COMP_WORDBREAKS" \
                  _ARGCOMPLETE=1 \
                  _ARGCOMPLETE_SUPPRESS_SPACE=$SUPPRESS_SPACE \
                  "$1" 8&gt;&1 9&gt;&2 1&gt;/dev/null 2&gt;/dev/null) )
    if [[ $? != 0 ]]; then
        unset COMPREPLY
    elif [[ $SUPPRESS_SPACE == 1 ]] && [[ "$COMPREPLY" =~ [=/:]$ ]]; then
        compopt -o nospace
    fi
}
complete -o nospace -F _python_argcomplete "az"
# end .bashrc

Also, it would be great to note that the expansion of the ${HOME} works just fine in PowerShell for Windows.

I think there may be a way to exclude the .bashrc in the volume mount, I have't identified the specific approach yet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d884a3fe-07cf-e518-085d-602425fe2480
* Version Independent ID: 1636994b-e193-74e2-9936-a07e43913326
* Content: [Run Azure CLI 2.0 in a Docker Container](https://docs.microsoft.com/en-us/cli/azure/run-azure-cli-docker?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/run-azure-cli-docker.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/run-azure-cli-docker.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Since the `.bashrc` is being mangled here, there may be a more appropriate way to pick up SSH keys directly (probably just by loading `${HOME}/.ssh` somewhere.) Will do some tests and see what can be changed. Thanks for bringing this issue to our attention.

**Comment by cicorias** [comment]
An interactive login shell that `/etc/profile` will be read, which by default should read all scripts - or `source`  --  `. <script>` each of them in `/etc/profile.d/` path.

However, doing `docker run --it ....` in the az-cli container, that is **non-interactive (afaik)**.  And that would look for `/etc/bash.bashrc`.  - if that script is modified, `/etc/bash.bashrc` that perhaps it can pickup the `az completion` initialization scripts.  Otherwise,

So, perhaps the necessary auto-completion bits / script can be in `/etc/profile.d`. ..  

This comes from https://shreevatsa.wordpress.com/2008/03/30/zshbash-startup-files-loading-order-bashrc-zshrc-etc/


> The issue is that Bash sources from a different file based on what kind of shell it thinks it is in. For an “interactive non-login shell”, it reads .bashrc, but for an “interactive login shell” it reads from the first of .bash_profile, .bash_login and .profile (only). There is no sane reason why this should be so; it’s just historical. Follows in more detail.

> For Bash, they work as follows. Read down the appropriate column. Executes A, then B, then C, etc. The B1, B2, B3 means it executes only the first of those files found.

```
+----------------+-----------+-----------+------+
|                |Interactive|Interactive|Script|
|                |login      |non-login  |      |
+----------------+-----------+-----------+------+
|/etc/profile    |   A       |           |      |
+----------------+-----------+-----------+------+
|/etc/bash.bashrc|           |    A      |      |
+----------------+-----------+-----------+------+
|~/.bashrc       |           |    B      |      |
+----------------+-----------+-----------+------+
|~/.bash_profile |   B1      |           |      |
+----------------+-----------+-----------+------+
|~/.bash_login   |   B2      |           |      |
+----------------+-----------+-----------+------+
|~/.profile      |   B3      |           |      |
+----------------+-----------+-----------+------+
|BASH_ENV        |           |           |  A   |
+----------------+-----------+-----------+------+
|                |           |           |      |
+----------------+-----------+-----------+------+
|                |           |           |      |
+----------------+-----------+-----------+------+
|~/.bash_logout  |    C      |           |      |
+----------------+-----------+-----------+------+
```

**Comment by sptramer** [comment]
It looks like changing the container build script to load the autocomplete elsewhere is a big task, and also one that might be affecting non-Docker builds. If you could file a ticket with this information with the engineering team, they may be able to address it: https://github.com/azure/azure-cli/issues/
