### ISSUE TITLE
Certificate verify failed

### ISSUE THREAD

**Issue by mattwoolnough** [Azure/azure-docs-cli-python#986]
when running az commands for the 1st time with Python 3 on mac, you encounter this error:

&lt;urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)&gt;

  error: error executing az
  status: 1

to resolve, use the info on this link https://stackoverflow.com/questions/41691327/ssl-sslerror-ssl-certificate-verify-failed-certificate-verify-failed-ssl-c

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d09ed623-c83f-6bae-639e-a5f9a31fe3bb
* Version Independent ID: c5d0d722-aacd-47a3-3fcf-982c02c4d0e9
* Content: [Install the Azure CLI for macOS](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-macos.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli-macos.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Can you let us know whether you installed Python 3 via `brew`, or through a Python installer?

**Comment by sptramer** [comment]
@mattwoolnough - Can you please provide the requested information? You may also need to file an issue with the engineering team to ensure that the `brew` install performs any correct dependency management. We will also need to know the version of macOS that you installed on.

Without additional information, this ticket will be closed on 10/12 as inactionable.

**Comment by sptramer** [comment]
Closing as unable to take action due to lack of information.
