### ISSUE TITLE
The MSI doesn't work on a windows 10 machine

### ISSUE THREAD

**Issue by tbithell** [Azure/azure-docs-cli-python#998]
I've downloaded and attempted to install this several times and have gotten no where.  I am never asked if the installer can make changes to my computer, it just quickly pops up and disappears and several minutes later it tells me that the installer has stopped working.  
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8246b90a-efb1-03ce-f642-d3eb2441fc30
* Version Independent ID: 2fdd20ef-7bd3-57bc-7957-93f4bb5377ce
* Content: [Install the Azure CLI for Windows](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-windows.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli-windows.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by tbithell** [comment]
It has never installed, so there is nothing to uninstall.

**Comment by tbithell** [comment]
Also, not sure where or what folder to delete, but don't see any related folders anywhere.  I was able to run it in a docker container.  I'd still like to sort out why I can't just install it, but I can at least move on in what I was working on.

**Comment by tbithell** [comment]
I was able to install it after uninstalling docker.  Any idea why docker would cause me to not be able to install software on a windows machine.

**Comment by sptramer** [comment]
I can't find any information on why Docker would prevent the installation of an MSI. We're probably going to need the following information:

* What version of Docker was installed
* Which version of the CLI you were attempting to install
* Windows version/build
* Which _date_ you downloaded the MSI on - this is relevant for determining if the MSI build was bad
* Errors generated by the MSI - You may need to [enable MSI logging](https://support.microsoft.com/en-us/help/223300/how-to-enable-windows-installer-logging)

(cc @JasonRShaver @yugangw-msft)

**Comment by tbithell** [comment]
Docker 10.06.0-ce-win72 (19098) Channel :stable 
Azure cli 2.0.44.2
Window 10 Enterprise Version 1803 (OS Build 17134.228)
Downloaded the MSI build yesterday, was able to use the same one to install it today after uninstalling docker
I don't know that I can do much by way of providing logs since I am no longer receiving the error and it is installed now.  I can look for logs from yesterday, I just need an idea of where to look.

**Comment by sptramer** [comment]
The current theory is that this was not an issue specific to the CLI, but rather some kind of bug in the MSI installation framework itself. We're continuing to investigate but this issue probably cannot be resolved on our end.

**Comment by sptramer** [comment]
@tbithell As a request from the engineering team for some information, can you please provide a log? Doing so as a gist/pastebin may be preferable if there's a lot of information or it's very long.

```
msiexec /i azure-cli-2.0.44.2.msi /l*v c:\log\foo.log
```

**Comment by sptramer** [comment]
@tbithell - Going to keep this ticket open for another week (until 10/12) at which point it will be closed for lack of action. Please provide the log information before then if you can. The engineering team believes this was a one-off issue, however.

**Comment by tbithell** [comment]
You can close it, I have no way to reproduce the error and it could very well have been a corrupt docker install or something like that.  I suspect that to be the case since it worked as soon as I deleted docker and since re-installing docker I haven't had any issue like it.
